// <auto-generated> by scripts/shake_icons.py - do not edit.
namespace KitLib.Icons;

public readonly partial struct MdiIcon
{
    public static readonly MdiIcon AnimationPlay = new("animation-play");
    public static readonly MdiIcon CalendarStar = new("calendar-star");
    public static readonly MdiIcon Check = new("check");
    public static readonly MdiIcon ChevronRight = new("chevron-right");
    public static readonly MdiIcon Close = new("close");
    public static readonly MdiIcon Console = new("console");
    public static readonly MdiIcon ContentCopy = new("content-copy");
    public static readonly MdiIcon ContentSave = new("content-save");
    public static readonly MdiIcon Delete = new("delete");
    public static readonly MdiIcon DragVertical = new("drag-vertical");
    public static readonly MdiIcon FilterVariant = new("filter-variant");
    public static readonly MdiIcon FolderOpen = new("folder-open");
    public static readonly MdiIcon Heart = new("heart");
    public static readonly MdiIcon Magnify = new("magnify");
    public static readonly MdiIcon Map = new("map");
    public static readonly MdiIcon Minus = new("minus");
    public static readonly MdiIcon Plus = new("plus");
    public static readonly MdiIcon PuzzleOutline = new("puzzle-outline");
    public static readonly MdiIcon Refresh = new("refresh");
    public static readonly MdiIcon Robot = new("robot");
    public static readonly MdiIcon Skull = new("skull");
    public static readonly MdiIcon SpeedometerMedium = new("speedometer-medium");
    public static readonly MdiIcon Star = new("star");
    public static readonly MdiIcon TextBoxOutline = new("text-box-outline");
    public static readonly MdiIcon TreasureChest = new("treasure-chest");
    public static readonly MdiIcon WeatherNight = new("weather-night");
    public static readonly MdiIcon WeatherSunny = new("weather-sunny");
    public static readonly MdiIcon ZipBox = new("zip-box");
}
