// <auto-generated> by scripts/shake_icons.py - do not edit.
namespace KitLib.ModPanel.Icons;

internal readonly partial struct MdiIcon
{
    public static readonly MdiIcon ChevronRight = new("chevron-right");
    public static readonly MdiIcon Minus = new("minus");
}
