using System.Reflection;
using System.Text;

if (args.Length < 2) {
    Console.Error.WriteLine("Usage: AbstractionsFacadeGen <abstractions.dll> <out.cs> [--search dir]...");
    return 1;
}

var abstractionsPath = Path.GetFullPath(args[0]);
var outPath = Path.GetFullPath(args[1]);
var search = new List<string>();
for (var i = 2; i < args.Length; i++) {
    if (args[i] == "--search" && i + 1 < args.Length)
        search.Add(Path.GetFullPath(args[++i]));
}

search.Insert(0, Path.GetDirectoryName(abstractionsPath)!);
var runtimeDir = Path.GetDirectoryName(typeof(object).Assembly.Location);
if (!string.IsNullOrEmpty(runtimeDir))
    search.Insert(0, runtimeDir);

var dlls = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
foreach (var dir in search) {
    if (!Directory.Exists(dir))
        continue;
    foreach (var dll in Directory.EnumerateFiles(dir, "*.dll"))
        dlls.Add(dll);
}

var resolver = new PathAssemblyResolver(dlls);
using var mlc = new MetadataLoadContext(resolver, "System.Runtime");
var asm = mlc.LoadFromAssemblyPath(abstractionsPath);
var sb = new StringBuilder();
sb.AppendLine("// <auto-generated />");
sb.AppendLine("#nullable enable");
sb.AppendLine("using System.Runtime.CompilerServices;");
sb.AppendLine();

foreach (var type in asm.GetExportedTypes().OrderBy(t => t.FullName, StringComparer.Ordinal)) {
    if (type.IsNested || type.Name.StartsWith('<'))
        continue;
    sb.AppendLine($"[assembly: TypeForwardedTo(typeof({FormatCSharpType(type)}))]");
}

Directory.CreateDirectory(Path.GetDirectoryName(outPath)!);
File.WriteAllText(outPath, sb.ToString());
return 0;

static string FormatCSharpType(Type type) {
    if (type.IsGenericType)
        type = type.GetGenericTypeDefinition();
    return "global::" + FormatName(type);
}

static string FormatName(Type type) {
    if (type.IsNested) {
        var parent = type.DeclaringType ?? throw new InvalidOperationException(type.FullName);
        return FormatName(parent) + "." + GenericLeaf(type);
    }

    var ns = type.Namespace;
    return string.IsNullOrEmpty(ns) ? GenericLeaf(type) : ns + "." + GenericLeaf(type);
}

static string GenericLeaf(Type type) {
    var name = type.Name;
    var tick = name.IndexOf('`');
    if (tick < 0)
        return name;
    var arity = int.Parse(name[(tick + 1)..]);
    return name[..tick] + "<" + new string(',', Math.Max(0, arity - 1)) + ">";
}
