#!/usr/bin/env python3
"""Detect STS2 + Godot, generate local.props and .vscode."""

from __future__ import annotations

import argparse
import html
import sys
from pathlib import Path

_SCRIPT_DIR = Path(__file__).resolve().parent
if str(_SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(_SCRIPT_DIR))

from lib.dotenv import load_dotenv  # noqa: E402
from lib.ensure_iconify_mdi import ensure_mdi_icons  # noqa: E402
from lib.godot import resolve_godot_path  # noqa: E402
from lib.steam import resolve_sts2_dir  # noqa: E402
from lib.vscode import (  # noqa: E402
    setup_debug_launch,
    write_vscode_files,
)


def _prop_line(name: str, value: str | None) -> str:
    if not value:
        return ""
    esc = html.escape(value, quote=False)
    return f"    <{name}>{esc}</{name}>\n"


def main() -> int:
    ap = argparse.ArgumentParser(description="DevMode repo init.")
    ap.add_argument(
        "--repo-root",
        type=Path,
        default=None,
        help="Repository root",
    )
    args = ap.parse_args()

    root = (args.repo_root or _SCRIPT_DIR.parent).resolve()
    load_dotenv(root / ".env")

    sts2_dir = resolve_sts2_dir()
    if not sts2_dir:
        print(
            "Slay the Spire 2 not found. Set STS2_DIR in .env.",
            file=sys.stderr,
        )
        return 1
    if not sts2_dir.is_dir():
        print(f"STS2 directory not found: {sts2_dir}", file=sys.stderr)
        return 1

    godot_path = resolve_godot_path()
    if not godot_path:
        print(
            "MegaDot/Godot not found. 'make pck' will not work. "
            "Set GODOT_PATH in .env."
        )

    props = _prop_line("Sts2Dir", str(sts2_dir))
    props += _prop_line("GodotPath", str(godot_path) if godot_path else None)

    local_props = root / "local.props"
    content = (
        "<!-- Generated by make init - do not commit -->\n"
        "<Project>\n"
        "  <PropertyGroup>\n"
        f"{props}"
        "  </PropertyGroup>\n"
        "</Project>\n"
    )
    local_props.write_text(content, encoding="utf-8")
    print(f"Generated {local_props}")
    print(f"  Sts2Dir   = {sts2_dir}")
    if godot_path:
        print(f"  GodotPath = {godot_path}")

    setup_debug_launch(sts2_dir)
    write_vscode_files(root, sts2_dir)

    ensure_mdi_icons(root)

    print("")
    print("Done. You can now run:")
    print("  make compile  -- dotnet build: DLL/manifest to game mods (no .pck)")
    print("  make pck      -- dotnet publish + Godot .pck to game mods")
    print("  make sync              -- build + deploy into game mods/DevMode/ (does not overwrite STS2-RitsuLib)")
    print("  make sync-framework-mods  -- copy DevMode STS2-RitsuLib NuGet into game (optional)")
    print("  make sync-launch       -- sync + launch game")
    print("  make launch            -- launch via Steam (macOS/Linux) or Sts2Dir exe (Windows)")
    print("  make sync-beta-launch  -- sync-beta + launch game")
    print("  make deploy    -- deploy from build/DevMode/ (after make build)")
    print("  make build     -- artifacts under build/DevMode/ only (no game copy)")
    print("  make upload-nuget  -- zip + NuGet pack/push (NUGET_API_KEY in .env)")
    print("  make upload-all    -- upload-github + upload-nexus + upload-nuget (one zip build)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
