#!/usr/bin/env python3
"""Detect STS2 + Godot, generate local.props and .vscode."""

from __future__ import annotations

import argparse
import html
import sys
from pathlib import Path

_SCRIPT_DIR = Path(__file__).resolve().parent
if str(_SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(_SCRIPT_DIR))

from lib.dotenv import load_release_config  # noqa: E402
from lib.ensure_iconify_mdi import ensure_mdi_icons  # noqa: E402
from lib.godot import resolve_godot_path  # noqa: E402
from lib.steam import resolve_sts2_dir  # noqa: E402
from lib.vscode import (  # noqa: E402
    setup_debug_launch,
    write_vscode_files,
)


def _prop_line(name: str, value: str | None) -> str:
    if not value:
        return ""
    esc = html.escape(value, quote=False)
    return f"    <{name}>{esc}</{name}>\n"


def main() -> int:
    ap = argparse.ArgumentParser(description="KitLib repo init.")
    ap.add_argument(
        "--repo-root",
        type=Path,
        default=None,
        help="Repository root",
    )
    args = ap.parse_args()

    root = (args.repo_root or _SCRIPT_DIR.parent).resolve()
    load_release_config(root)

    sts2_dir = resolve_sts2_dir()
    if not sts2_dir:
        print(
            "Slay the Spire 2 not found. Install via Steam or set STS2_DIR for a custom path.",
            file=sys.stderr,
        )
        return 1
    if not sts2_dir.is_dir():
        print(f"STS2 directory not found: {sts2_dir}", file=sys.stderr)
        return 1

    godot_path = resolve_godot_path()
    if not godot_path:
        print("MegaDot/Godot not found. 'make pck' will not work. " "Set GODOT_PATH in .env.")

    from lib.sts2_profiles import resolve_compile_profile

    props = _prop_line("Sts2Dir", str(sts2_dir))
    profile = resolve_compile_profile(
        repo_root=root,
        sts2_dir=sts2_dir,
        allow_game_inference=True,
    )
    props += _prop_line("Sts2Profile", profile)
    props += _prop_line("GodotPath", str(godot_path) if godot_path else None)

    local_props = root / "local.props"
    content = "<!-- Generated by make init - do not commit -->\n" "<Project>\n" "  <PropertyGroup>\n" f"{props}" "  </PropertyGroup>\n" "</Project>\n"
    local_props.write_text(content, encoding="utf-8")
    print(f"Generated {local_props}")
    print(f"  Sts2Dir   = {sts2_dir}")
    print(f"  Sts2Profile = {profile}")
    if godot_path:
        print(f"  GodotPath = {godot_path}")

    setup_debug_launch(sts2_dir)
    write_vscode_files(root, sts2_dir)

    ensure_mdi_icons(root)

    dual_hint = True
    for profile in ("stable", "beta"):
        try:
            from lib.sts2_profiles import ref_is_valid, ref_root

            if not ref_is_valid(ref_root(root, profile)):
                dual_hint = False
                break
        except Exception:
            dual_hint = False
            break
    if dual_hint:
        print("")
        print("STS2 ref DLLs present under eng/sts2-refs/.")
        print("  make build-profiles  -- compile against stable + beta refs")
        print("  make verify-profiles -- build-profiles + check-api (pre-release)")
    else:
        print("")
        print("Dual-profile refs missing under eng/sts2-refs/.")
        print("  Switch Steam branch, then: make capture-sts2-ref PROFILE=stable|beta")

    print("")
    print("Done. You can now run:")
    print("  make compile  -- dotnet build: DLL/manifest to game mods (no .pck)")
    print("  make pck      -- dotnet publish + Godot .pck to game mods")
    print("  make sync              -- build + deploy into game mods/KitLib/ (does not overwrite STS2-RitsuLib)")
    print("  make sync-framework-mods  -- copy DevMode STS2-RitsuLib NuGet into game (optional)")
    print("  make sync-launch       -- sync + launch game")
    print("  make launch            -- launch via Steam (macOS/Linux) or Sts2Dir exe (Windows)")
    print("  make deploy    -- deploy from build/KitLib/ (after make build)")
    print("  make build     -- artifacts under build/KitLib/ only (no game copy)")
    print("  make upload-nuget  -- zip + NuGet pack/push (NUGET_API_KEY in .env)")
    print("  make upload-steam  -- Workshop upload (STS2_MOD_UPLOADER in .env)")
    print("  make upload-all    -- upload-github + upload-nexus + upload-nuget + upload-steam (one zip build)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
